config/routes.rb
Rails.application.routes.draw do
  
  root 'application#index'
  resources :teammates
  get 'lunchdates', to: 'lunchdates#index'
  get 'lunchdates/create'

end

app/models/lunch_date.rb
class LunchDate < ActiveRecord::Base
    belongs_to :teammate_a, :class_name => :Teammate
    belongs_to :teammate_b, :class_name => :Teammate
    
    def LunchDate.create_lunch_dates
        
        LunchDate.destroy_all
        
        # Get array of workdays in current month
        work_days = []
        today = Date.today
        day = today.beginning_of_month
        month_end = today.end_of_month
        while day <= month_end
            if !day.saturday? && !day.sunday?
                work_days.push(day)
            end
            day = day + 1
        end
        
        # Create random list of teammates
        shuffled_teammates = []
        loop do
            shuffled_teammates = shuffled_teammates.concat(Teammate.all.shuffle)
            break if shuffled_teammates.length >= work_days.length * 2
        end
        # Create lunch dates, making sure people don't pay more than three times (first teammate pays)
        count = {}
        work_days.each_with_index do |work_day, i|
            i1 = i*2 # index of first teammate
            i2 = i1 + 1 # index of second teammate
            first_teammate_buy_count = count[shuffled_teammates[i1][:name]]
            second_teammate_buy_count = count[shuffled_teammates[i2][:name]]

            # If first teammate has paid for lunch at least two more times than second teammate, swap places.
            if first_teammate_buy_count && 
                (first_teammate_buy_count - (second_teammate_buy_count ? second_teammate_buy_count : 0)) >= 2
                shuffled_teammates[i1], shuffled_teammates[i2] = shuffled_teammates[i2], shuffled_teammates[i1]
            # Check if first teammate has paid for three lunches or more
            elsif first_teammate_buy_count && first_teammate_buy_count >= 3
                # If so, check if second teammate has paid for less than three lunches
                if !second_teammate_buy_count || second_teammate_buy_count < 3
                    # If so, swap with first teammate
                    shuffled_teammates[i1], shuffled_teammates[i2] = shuffled_teammates[i2], shuffled_teammates[i1]
                else # Find next person in shuffled list who has payed for less than three lunches
                    if i2 < shuffled_teammates.length - 1
                        ((i2 + 1)..shuffled_teammates.length - 1).each do |n|
                            if count.key?(shuffled_teammates[n][:name])  && count[shuffled_teammates[n][:name]] < 3
                                # Swap
                                shuffled_teammates[i1], shuffled_teammates[n] = shuffled_teammates[n], shuffled_teammates[i1]
                                break
                            end
                        end
                    end
                end
            end
            
            count[shuffled_teammates[i1][:name]] = count[shuffled_teammates[i1][:name]] ? count[shuffled_teammates[i1][:name]] + 1 : 1
            LunchDate.create(teammate_a: shuffled_teammates[i1], teammate_b: shuffled_teammates[i2], date: work_day)
            
        end        
    end
    
end

app/models/teammate.rb
class Teammate < ActiveRecord::Base
    has_many(:lunch_dates, :foreign_key => :teammate_a_id, :dependent => :destroy)
    has_many(:reverse_lunch_dates, :class_name => :LunchDate,
      :foreign_key => :teammate_b_id, :dependent => :destroy)
    
    attr_accessor :bio, :location, :pic_url
    
    def get_all_lunch_dates
      all_dates = []
      self.lunch_dates.each do |date|
        all_dates.push({teammate: date.teammate_b.name, date: date.date, pay: true})
      end
      self.reverse_lunch_dates.each do |date|
        all_dates.push({teammate: date.teammate_a.name, date: date.date, pay: false})
      end
      all_dates.sort_by!{|date| date[:date]}
      return all_dates
    end
    
    def load_twitter_data
      begin
        user_twitter = self[:twitter_username] ? $twitter.user(self[:twitter_username]) : nil
      rescue Exception
        puts 'Twitter user not found'
        user_twitter = nil
      end
      if user_twitter
        @bio = user_twitter.description
        @location = user_twitter.location
        @pic_url = user_twitter.profile_image_url
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def index
    @lunchdate = LunchDate.find_by date: Date.today
  end
  
end

app/controllers/lunchdates_controller.rb
class LunchdatesController < ApplicationController

  def index
    @lunchdates = LunchDate.all
  end
  
  def create
    LunchDate.create_lunch_dates
    redirect_to lunchdates_url
  end
  
end

app/controllers/teammates_controller.rb
class TeammatesController < ApplicationController
  before_action :set_teammate, only: [:show, :edit, :update, :destroy]

  # GET /teammates
  # GET /teammates.json
  def index
    
    @teammates = Teammate.all
    
    @teammates.each do |teammate|
      teammate.load_twitter_data
    end
      
      
    
  end

  # GET /teammates/1
  # GET /teammates/1.json
  def show
    @lunchdates = @teammate.get_all_lunch_dates
  end

  # GET /teammates/new
  def new
    @teammate = Teammate.new
  end

  # GET /teammates/1/edit
  def edit
  end

  # POST /teammates
  # POST /teammates.json
  def create
    @teammate = Teammate.new(teammate_params)

    respond_to do |format|
      if @teammate.save
        format.html { redirect_to @teammate, notice: 'Teammate was successfully created.' }
        format.json { render :show, status: :created, location: @teammate }
      else
        format.html { render :new }
        format.json { render json: @teammate.errors, status: :unprocessable_entity }
      end
    end
    LunchDate.create_lunch_dates
  end

  # PATCH/PUT /teammates/1
  # PATCH/PUT /teammates/1.json
  def update
    respond_to do |format|
      if @teammate.update(teammate_params)
        format.html { redirect_to @teammate, notice: 'Teammate was successfully updated.' }
        format.json { render :show, status: :ok, location: @teammate }
      else
        format.html { render :edit }
        format.json { render json: @teammate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teammates/1
  # DELETE /teammates/1.json
  def destroy
    @teammate.destroy
    respond_to do |format|
      format.html { redirect_to teammates_url, notice: 'Teammate was successfully destroyed.' }
      format.json { head :no_content }
    end
    LunchDate.create_lunch_dates
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teammate
      @teammate = Teammate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teammate_params
      params.require(:teammate).permit(:name, :twitter_username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lunchdates_helper.rb
module LunchdatesHelper
end

app/helpers/teammates_helper.rb
module TeammatesHelper
end

app/views/application/index.html.erb
<div class="jumbotron text-center" style="margin-top: 50px;">
    <h1 class="display-3">Lunch Dates</h1>
    <p class="lead">Automatically match up teammates to have lunch together!</p>
    <p><%= link_to 'Teammates', teammates_path, class: "btn btn-lg btn-success", role: "button" %>
      <%= link_to 'Lunch Schedule', lunchdates_path, class: "btn btn-lg btn-success", role: "button" %></p>
    <div class="card" style="width: 20rem; margin: 0 auto;">
      <div class="card-body">
        <h4 class="card-title">Today's Lunch Date</h4>
        <p class="card-text">
          <% if @lunchdate %>
          <strong><%= @lunchdate.teammate_a.name %></strong> is treating <strong><%= @lunchdate.teammate_b.name %></strong> to lunch.
          <% else %>
          No lunch date scheduled today.
          <% end %>
          <% if Date.today.saturday? || Date.today.sunday? %>
          <br> <i>Lunches only scheduled on weekdays.</i>
          <% end %>
        </p>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lunch Dates</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Lunch Dates', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Teammates', teammates_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Schedule', lunchdates_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/lunchdates/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to "Recreate Lunch Dates", lunchdates_create_path, class: "btn btn-danger float-right" %>
<h1>Full Schedule</h1>
<ul class="list-group">
<% @lunchdates.each do |date| %>
  <li class="list-group-item text-center <%= date.date.today? ? 'list-group-item-secondary' : '' %>"><span class="badge badge-secondary"><%= date.date.strftime('%A, %B %d') %></span><br>
  <strong><%= link_to date.teammate_a.name, date.teammate_a %></strong> is treating <strong><%= link_to date.teammate_b.name, date.teammate_b %></strong> </strong> to lunch.</li>
<% end %>
</ul>

app/views/teammates/_form.html.erb
<%= form_for(@teammate) do |f| %>
  <% if @teammate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teammate.errors.count, "error") %> prohibited this teammate from being saved:</h2>

      <ul>
      <% @teammate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :twitter_username %><br>
    <%= f.text_field :twitter_username %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-success" %>
  </div>
<% end %>

app/views/teammates/edit.html.erb
<h1>Editing Teammate</h1>
<div class="card">
    <div class="card-block text-center">
        <%= render 'form' %>
        
        <%= link_to 'Back', @teammate %> |
        <%= link_to 'Destroy', @teammate, method: :delete, data: { confirm: 'Are you sure?' } %> 
    </div>
</div>

app/views/teammates/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New Teammate', new_teammate_path, class: "btn btn-success float-right" %>
<h1>Teammates</h1>
  <div class="row">
  <% @teammates.each do |teammate| %>
    <div class="col-lg-3">
      <div class="card">
        <div class="card-block">
          <h4 class="card-title"><%= teammate.name %>
            <% if teammate.twitter_username.length > 0 %>
              <a href="https://twitter.com/<%= teammate.twitter_username %>" class="float-right">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
            <% end %>
          </h4>
          <h6 class="card-subtitle mb-2 text-muted"><%= teammate.location %></h6>
          <p class="card-text clearfix"><% if teammate.pic_url %><img src="<%= teammate.pic_url %>"><% end %><%= teammate.bio %></p>
            <%= link_to 'Show Lunch Dates', teammate, class: "btn btn-sm btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
  </div>

app/views/teammates/new.html.erb
<h1>New Teammate</h1>

<%= render 'form' %>

<%= link_to 'Back', teammates_path %>

app/views/teammates/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @teammate.name %>'s lunch dates this month</h1>
<div class="card">
  <div class="card-block">
    <div class="text-center">
      <%= link_to 'Edit Account', edit_teammate_path(@teammate) %> |
      <%= link_to 'Back to Teammates', teammates_path %>
    </div>
    <div class="text-center">
      <% @lunchdates.each do |date| %>
       <p></p><span class="badge badge-secondary"><%= date[:date] %></span>
       Lunch with <strong><%= date[:teammate] %></strong>
       <% if date[:pay] %> (paying)<% end %></p>
      <% end %>      
    </div>
  </div>
</div>  